### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by dennissergeev** [ueapy/enveast_python_course_materials#9]
Topics to cover:
- [ ] reading netCDF dataset

- [ ] reading text files

- [ ] data manipulation, e.g. averaging / regridding / interpolating

- [ ] plotting results on a map using either cartopy or basemap

- [ ] using subplots in matplotlib

**Comment by dennissergeev** [comment]
@tiagoams, @abstractwisdom check if you are OK with the instructions for the project (22-Final-Project.ipynb)

**Comment by tiagoams** [comment]
This seems fine. I will add context so that the problem is not abstract.
